name: studenthub
description: A Flutter app for students and admins with role-based dashboards.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  curved_navigation_bar: ^1.0.6
  intl: ^0.19.0
  uuid: ^4.5.1
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.5.6
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
