name: studenthub
description: A Flutter app for students and admins with role-based dashboards.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Updated Packages
  provider: ^6.1.2
  curved_navigation_bar: ^1.0.6
  intl: ^0.19.0
  uuid: ^4.5.1
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.5.6
  shared_preferences: ^2.2.3
  
  # New packages for enhanced features
  go_router: ^14.2.3
  file_picker: ^8.0.6
  firebase_core: ^3.4.0
  firebase_messaging: ^15.1.0
  flutter_local_notifications: ^17.2.2
  connectivity_plus: ^6.0.5
  image_picker: ^1.1.2
  url_launcher: ^6.3.0
  flutter_dotenv: ^5.1.0
  equatable: ^2.0.5
  dio: ^5.6.0
  cached_network_image: ^3.4.1
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  # This is the latest version compatible with your SDK
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env
