// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCG7C3eOb54l8lx_mmMB0YYBbj806SvtE',
    appId: '1:282250959705:web:YOUR_WEB_APP_ID',
    messagingSenderId: '282250959705',
    projectId: 'studenthub-b6c51',
    authDomain: 'studenthub-b6c51.firebaseapp.com',
    storageBucket: 'studenthub-b6c51.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCG7C3eOb54l8lx_mmMB0YYBbj806SvtE',
    appId: '1:282250959705:android:3b9494e78d0064a75a8a48',
    messagingSenderId: '282250959705',
    projectId: 'studenthub-b6c51',
    storageBucket: 'studenthub-b6c51.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCG7C3eOb54l8lx_mmMB0YYBbj806SvtE',
    appId: '1:282250959705:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '282250959705',
    projectId: 'studenthub-b6c51',
    storageBucket: 'studenthub-b6c51.firebasestorage.app',
    iosBundleId: 'com.example.studenthub',
  );
}
